POST https://ota-api.herokuapp.com/api/blogapp/users/signup HTTP/1.1
content-type: application/json

{
    "username":""
}



###
GET https://ota-api.herokuapp.com/api/blogapp/blogs HTTP/1.1


###
GET url HTTP/1.1

###
PUT url HTTP/1.1
content-type: application/json
{}


###
DELETE url HTTP/1.1