POST http://localhost:5000/api/superapp/users/signup HTTP/1.1
content-type: application/json



###
GET http://localhost:5000/api/superapp/users/profile HTTP/1.1


###
GET url HTTP/1.1

###
PUT url HTTP/1.1
content-type: application/json
{}


###
DELETE url HTTP/1.1